# Generated by Django 6.0.5 on 2026-05-13 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Creator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("added_date", models.DateTimeField(verbose_name="addition date")),
            ],
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ME", "Animation Meme"),
                            ("MV", "Music Video"),
                            ("OT", "Other Video"),
                        ],
                        default="ME",
                        max_length=2,
                    ),
                ),
                ("entry_name", models.CharField(max_length=320)),
                ("added_date", models.DateTimeField(verbose_name="addition date")),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="entries.creator",
                    ),
                ),
            ],
        ),
    ]
