# Generated by Django 6.0.5 on 2026-05-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="link",
            field=models.URLField(
                default="https://www.youtube.com/watch?v=0Ktk-b9R-0s"
            ),
            preserve_default=False,
        ),
    ]
