# Generated by Django 6.0.5 on 2026-05-13 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0003_entry_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="upload_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="original upload date"
            ),
            preserve_default=False,
        ),
    ]
