# Generated by Django 6.0.5 on 2026-05-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0004_entry_upload_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="upload_date",
            field=models.DateField(verbose_name="original upload date"),
        ),
    ]
