# Generated by Django 6.0.5 on 2026-05-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0005_alter_entry_upload_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
