# Generated by Django 6.0.5 on 2026-05-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0006_entry_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="category",
            field=models.CharField(
                choices=[
                    ("Animation Meme", "Animation Meme"),
                    ("Music Video", "Music Video"),
                    ("Other Video", "Other Video"),
                ],
                default="Animation Meme",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="thumbnails/entries/%Y/%m/%d"),
        ),
    ]
