# Generated by Django 6.0.5 on 2026-05-13 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0007_alter_entry_category_alter_entry_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="inspired",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inspired_by",
                to="entries.entry",
            ),
        ),
    ]
