# Generated by Django 6.0.5 on 2026-05-13 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0008_entry_inspired"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="original_meme",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_meme",
                to="entries.entry",
            ),
        ),
    ]
