# Generated by Django 6.0.5 on 2026-05-13 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0009_entry_original_meme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="inspired",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inspired_by",
                to="entries.entry",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="original_meme",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_meme",
                to="entries.entry",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="thumbnails/entries/%Y/%m/%d"
            ),
        ),
    ]
