# Generated by Django 6.0.5 on 2026-05-13 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0010_alter_entry_inspired_alter_entry_original_meme_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="original_meme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_meme",
                to="entries.entry",
            ),
        ),
    ]
