# Generated by Django 6.0.5 on 2026-05-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0011_alter_entry_original_meme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="inspired",
        ),
        migrations.AddField(
            model_name="entry",
            name="inspired",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="inspired_by", to="entries.entry"
            ),
        ),
    ]
