# Generated by Django 6.0.5 on 2026-05-13 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0012_remove_entry_inspired_entry_inspired"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="inspired",
        ),
        migrations.AddField(
            model_name="entry",
            name="inspired",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inspired_by",
                to="entries.entry",
            ),
        ),
    ]
