# Generated by Django 6.0.5 on 2026-05-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0013_remove_entry_inspired_entry_inspired"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="inspired",
        ),
        migrations.AddField(
            model_name="entry",
            name="inspired",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="inspired_by", to="entries.entry"
            ),
        ),
    ]
