# Generated by Django 6.0.5 on 2026-05-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0014_remove_entry_inspired_entry_inspired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="inspired",
            field=models.ManyToManyField(
                related_name="inspired_by", to="entries.entry"
            ),
        ),
    ]
