# Generated by Django 6.0.5 on 2026-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0015_alter_entry_inspired"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="inspired",
        ),
        migrations.AddField(
            model_name="entry",
            name="related_memes",
            field=models.ManyToManyField(to="entries.entry"),
        ),
    ]
