# Generated by Django 6.0.5 on 2026-05-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0016_remove_entry_inspired_entry_related_memes"),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="thumbnails/creators/%Y/%m/%d"
            ),
        ),
    ]
