# Generated by Django 6.0.5 on 2026-05-14 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0017_creator_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memes_made",
                to="entries.creator",
            ),
        ),
    ]
