# Generated by Django 6.0.5 on 2026-05-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0018_alter_entry_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="related_memes",
            field=models.ManyToManyField(blank=True, to="entries.entry"),
        ),
    ]
