# Generated by Django 6.0.5 on 2026-05-14 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0019_alter_entry_related_memes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="related_memes",
        ),
        migrations.AddField(
            model_name="entry",
            name="related_memes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="entries.entry",
            ),
        ),
    ]
