# Generated by Django 6.0.5 on 2026-05-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0020_remove_entry_related_memes_entry_related_memes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="related_memes",
        ),
        migrations.AddField(
            model_name="entry",
            name="related_memes",
            field=models.ManyToManyField(blank=True, to="entries.entry"),
        ),
    ]
