# Generated by Django 6.0.5 on 2026-05-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0021_remove_entry_related_memes_entry_related_memes"),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Hiatus", "Hiatus"),
                    ("Inactive", "Inactive"),
                    ("Missing / Gone", "Missing / Gone"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=32,
            ),
        ),
    ]
