# Generated by Django 6.0.5 on 2026-05-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0023_alter_creator_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creator",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entry",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=320)),
                ("added_date", models.DateTimeField(verbose_name="addition date")),
                ("thumbnail", models.URLField(blank=True, null=True)),
                ("link", models.URLField(verbose_name="more info")),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="characters",
                        to="entries.creator",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entry",
            name="characters",
            field=models.ManyToManyField(
                blank=True, related_name="meme_appearances", to="entries.character"
            ),
        ),
    ]
